[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_BACKEND_URL = "https://ai-code-reviewer-and-dsa-guide.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
